# -*- coding: utf-8 -*-
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import List, Optional
import os
from pathlib import Path

from config import get_config
from core.search_service import reset_search_service
from storage import DatabaseManager

router = APIRouter()

class SystemConfig(BaseModel):
    # 自选股
    stock_list: str  # 逗号分隔
    
    # 数据源
    tushare_token: Optional[str] = None
    
    # AI 模型配置
    gemini_request_delay: float = 2.0
    
    openai_api_key: Optional[str] = None
    openai_base_url: Optional[str] = None
    openai_model: str = "gpt-4o-mini"
    
    # 搜索引擎
    tavily_api_keys: str  # 逗号分隔
    serpapi_keys: str  # 逗号分隔
    
    # 通知
    wechat_webhook_url: Optional[str] = None
    wechat_enabled: bool = True
    mattermost_webhook_url: Optional[str] = None
    mattermost_enabled: bool = True
    
    # 系统与定时任务
    schedule_enabled: bool = False
    schedule_time: str = "18:00"
    market_review_enabled: bool = True
    max_workers: int = 3
    debug: bool = False

@router.get("/")
async def get_system_config():
    """获取当前配置"""
    config = get_config()
    return {
        "stock_list": ",".join(config.stock_list),
        "tushare_token": config.tushare_token,
        
        "gemini_request_delay": config.gemini_request_delay,
        
        "openai_api_key": config.openai_api_key,
        "openai_base_url": config.openai_base_url,
        "openai_model": config.openai_model,
        
        "tavily_api_keys": ",".join(config.tavily_api_keys),
        "serpapi_keys": ",".join(config.serpapi_keys),
        
        "wechat_webhook_url": config.wechat_webhook_url,
        "wechat_enabled": config.wechat_enabled,
        "mattermost_webhook_url": config.mattermost_webhook_url,
        "mattermost_enabled": config.mattermost_enabled,
        
        "schedule_enabled": config.schedule_enabled,
        "schedule_time": config.schedule_time,
        "market_review_enabled": config.market_review_enabled,
        "max_workers": config.max_workers,
        "debug": config.debug,
    }

@router.post("/")
async def save_system_config(new_config: SystemConfig):
    """保存配置到 .env 文件"""
    env_path = Path(__file__).parent.parent.parent / '.env'
    
    # 构建要保存的内容
    env_content = f"""# Auto-generated by Web UI
# ===================================
# 自选股与数据源
# ===================================
STOCK_LIST={new_config.stock_list}
TUSHARE_TOKEN={new_config.tushare_token or ''}

# ===================================
# AI 模型配置
# ===================================
GEMINI_REQUEST_DELAY={new_config.gemini_request_delay}

OPENAI_API_KEY={new_config.openai_api_key or ''}
OPENAI_BASE_URL={new_config.openai_base_url or ''}
OPENAI_MODEL={new_config.openai_model}

# ===================================
# 搜索引擎配置
# ===================================
TAVILY_API_KEYS={new_config.tavily_api_keys}
SERPAPI_KEYS={new_config.serpapi_keys}

# ===================================
# 通知配置
# ===================================
WECHAT_WEBHOOK_URL={new_config.wechat_webhook_url or ''}
WECHAT_ENABLED={str(new_config.wechat_enabled).lower()}
MATTERMOST_WEBHOOK_URL={new_config.mattermost_webhook_url or ''}
MATTERMOST_ENABLED={str(new_config.mattermost_enabled).lower()}

# ===================================
# 系统与定时任务
# ===================================
SCHEDULE_ENABLED={str(new_config.schedule_enabled).lower()}
SCHEDULE_TIME={new_config.schedule_time}
MARKET_REVIEW_ENABLED={str(new_config.market_review_enabled).lower()}
MAX_WORKERS={new_config.max_workers}
DEBUG={str(new_config.debug).lower()}

# ===================================
# 固定配置 (Web UI 不修改)
# ===================================
DATABASE_PATH=./data/stock_analysis.db
LOG_DIR=./logs
LOG_LEVEL=INFO
"""
    
    try:
        with open(env_path, 'w', encoding='utf-8') as f:
            f.write(env_content)
        
        # 强制重新加载配置
        from config import Config
        Config.reload()
        
        # 同时重置相关服务的单例，确保使用新配置
        from core.search_service import reset_search_service
        reset_search_service()
        
        # 重置数据库连接（如果路径改变）
        from storage import DatabaseManager
        DatabaseManager.reset_instance()
        
        return {"status": "success", "message": "配置已更新并生效"}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"保存失败: {str(e)}")